name: Quote
on: 
  push:
    branches : [main]
  workflow_dispatch:

jobs:
  my-job:
    name: Greeting Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: |
        echo Hello there!

